### ISSUE TITLE
US-5

### ISSUE THREAD

**Issue by Sullynobugz** [Sullynobugz/capstone-project#12]
## Value proposition

As a user, I want my daily quota from the implementation page to correlate with the progress bar on the weekday page, so I can visually track my progress throughout the day.

## Acceptance criteria

- [ ] Daily quota from the implementation page is represented as 100% on the progress bar
- [ ] Actual progress is shown as a percentage of the daily quota
- [ ] Progress bar fills up based on habits tracked
- [ ] Progress bar is displayed on the weekday page

## Tasks

- [ ] Implement link between implementation page details and progress bar
- [ ] Calculate and display progress as a percentage of daily quota
- [ ] Update progress bar in real-time based on tracked habits
