### ISSUE TITLE
US-2

### ISSUE THREAD

**Issue by Sullynobugz** [Sullynobugz/capstone-project#3]
## Value proposition

As a user,
I want to define goals, frequency, intensity, starting point, and weekly increment for a habit,
to effectively implement and track my progress.

## Description
<img width="330" alt="Bildschirmfoto 2023-04-26 um 16 03 13" src="https://user-images.githubusercontent.com/122908563/234601495-41ec1561-16eb-4c25-aa92-7c946eb35cf9.png">

## Acceptance criteria

- [ ] User can select a habit
- [ ] Form for defining goal, frequency, intensity, starting point, and weekly increment
- [ ] submit button saves implementation details

## Tasks

- [ ] Create a habit selection interface
- [ ] Create submit button to set implementation details
- [ ] Create submit button
