### ISSUE TITLE
US-4

### ISSUE THREAD

**Issue by Sullynobugz** [Sullynobugz/capstone-project#5]
## Value proposition

As a user,
I want to track and manage my progress on a selected habit,
to stay motivated and informed.

## Description
<img width="315" alt="Bildschirmfoto 2023-04-26 um 17 20 50" src="https://user-images.githubusercontent.com/122908563/234623293-dc1c205b-944e-44f9-b0cc-fb9b2bc92b0f.png">

## Acceptance criteria

- [ ] Header: "Progress on <habit>"
- [ ] Slider to check off progress
- [ ] Display progress on the habits list page
- [ ] Info/motivation window at the bottom

## Tasks

- [ ] Create header with habit name
- [ ] Implement slider for tracking progress
- [ ] Update progress on the habits list page
- [ ] Add info/motivation window at the bottom
